const ACTIONS = {
  //FETCH DATA
  GET_PIZZA_START: 'GET_PIZZA_START',
  GET_PIZZA_SUCCESS: 'GET_PIZZA_SUCCESS',
  GET_PIZZA_ERROR: 'GET_PIZZA_ERROR',
  //CART DATA
  ADD_CART_ITEM: 'ADD_CART_ITEM',
  DELETE_CART_ITEM: 'DELETE_CART_ITEM',
  ERASE_CART: 'ERASE_CART',
  //USER AUTH
  SIGN_IN_START: 'SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_ERROR: 'SIGN_IN_ERROR',
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',
  //Refresh Token
  REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',
  REFRESH_TOKEN_ERROR: 'REFRESH_TOKE_ERROR',
};
export default ACTIONS;
