const ACTIONS = {
  //FETCH DATA
  GET_PIZZA_START: 'GET_PIZZA_START',
  GET_PIZZA_SUCCESS: 'GET_PIZZA_SUCCESS',
  GET_PIZZA_ERROR: 'GET_PIZZA_ERROR',
  //CART DATA
  ADD_CART_ITEM: 'ADD_CART_ITEM',
  DELETE_CART_ITEM: 'DELETE_CART_ITEM',
  ERASE_CART: 'ERASE_CART',
};
export default ACTIONS;
